SPRING_PROFILES_ACTIVE=${project.springProfile}
SERVER_PORT=${project.serverPort?c}
SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
SPRING_CLOUD_NACOS_USERNAME=${nacos.username}
SPRING_CLOUD_NACOS_PASSWORD=${nacos.password}
