# ${project.projectName} Deployment Package

This package was generated by BootDeployKit for a Spring Boot Docker deployment.

## Files

- `Dockerfile`: container image definition
- `docker-compose.yml`: runtime stack
- `.env.example`: environment variable example
- `config/application-prod.yml`: Spring Boot production configuration
- `scripts/deploy.sh`: build and start the stack
- `scripts/restart.sh`: restart the application
- `scripts/logs.sh`: follow application logs

## Requirements

- Docker
- Docker Compose v2

## Usage

1. Copy your Spring Boot JAR file into this directory as `${project.jarFileName}`.
2. Copy `.env.example` to `.env` and update values for your environment.
3. Run `chmod +x scripts/*.sh`.
4. Run `./scripts/deploy.sh`.
5. Open `http://localhost:${project.serverPort?c}`.

## Operations

- Logs: `./scripts/logs.sh`
- Restart: `./scripts/restart.sh`
- Stop: `docker compose down`

## Security Notes

Review all generated settings before production use. Do not commit `.env` files with secrets.
